version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    environment:
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}
    restart: unless-stopped